version: 2
jobs:
  build:
    working_directory: ~/angular-cli-circleci
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: lint
          command: yarn affected:lint --base=master --parallel
      - run:
          name: build
          command: yarn affected:build --all --prod --no-progress --parallel
      - run:
          name: test
          command: yarn affected:test --base=master --parallel
      - deploy:
          name: Deploy
          # Deploy script from:
          # https://blog.frederikring.com/articles/deploying-github-pages-circle-ci/
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email "circleci@circleci.com"
              git config --global user.name "Circle CI Automated committer"

              git clone $CIRCLE_REPOSITORY_URL out

              cd out
              git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
              git rm -rf .
              cd ..

              yarn install
              yarn run build

              cp -a dist/apps/kythe-ui/. out/.

              mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
              cd out

              echo "kythe.achew22.com" > CNAME

              git add -A
              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

              git push origin $TARGET_BRANCH
            fi
